import {
    Smartphone,
    Monitor,
    Cpu,
    Camera,
    Battery,
    Zap,
    Weight,
    Ruler,
    Palette,
    Volume2,
    Wifi,
    Bluetooth,
    Usb,
    Settings,
    Star,
    TrendingUp,
    HardDrive,
    Database,
    Eye,
    Maximize,
    Headphones,
    Mic,
    Signal,
    Radio,
    Gauge,
    Activity,
    Package,
    Layers,
    Power,
    Plug,
    Archive,
    Folder,
    Shield,
    Lock,
    Gamepad,
    Trophy,
    Car,
    Fuel,
    Clock,
    Calendar,
    MapPin,
    Thermometer,
    Wind,
    Sun,
} from 'lucide-react';

export const iconMap = {
    smartphone: Smartphone,
    monitor: Monitor,
    cpu: Cpu,
    camera: Camera,
    battery: Battery,
    zap: Zap,
    weight: Weight,
    ruler: Ruler,
    palette: Palette,
    volume: Volume2,
    wifi: Wifi,
    bluetooth: Bluetooth,
    usb: Usb,
    settings: Settings,
    star: Star,
    'trending-up': TrendingUp,
    'hard-drive': HardDrive,
    database: Database,
    eye: Eye,
    maximize: Maximize,
    headphones: Headphones,
    mic: Mic,
    signal: Signal,
    radio: Radio,
    gauge: Gauge,
    activity: Activity,
    package: Package,
    layers: Layers,
    power: Power,
    plug: Plug,
    archive: Archive,
    folder: Folder,
    shield: Shield,
    lock: Lock,
    gamepad: Gamepad,
    trophy: Trophy,
    car: Car,
    fuel: Fuel,
    clock: Clock,
    calendar: Calendar,
    'map-pin': MapPin,
    thermometer: Thermometer,
    wind: Wind,
    sun: Sun,
};
